---
minimum_pre_commit_version: 1.15.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [-l 100]
        language_version: python3.6
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.4.4
#    hooks:
#      - id: pylint
#        name: PyLint
#        args: [--output-format=parseable, --rcfile=.pylintrc]
